name: live_score
description: Live score app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  intl: ^0.17.0
  hexcolor: ^2.0.7
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  internet_connection_checker: ^0.0.1+4
  fluttertoast: ^8.0.9
  http: ^0.13.5
  url_launcher: ^6.1.8
  google_mobile_ads: ^2.3.0
  share_plus: ^6.3.0
  device_preview: ^1.1.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoapp.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logoapp.jpg


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/no_matches.png
    - assets/images/no_stats.png
    - assets/images/Football_playground.png
    - assets/images/substitute.jpg
